# Generated by Django 2.2.15 on 2020-08-24 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_fk_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='jkjk',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='homepage_jkjk', to='home.CustomText'),
        ),
    ]
